<?
require("/etc/cdrtool/global.inc");

page_open(
    array("sess" => "CDRTool_Session",
          "auth" => "CDRTool_Auth",
          "perm" => "CDRTool_Perm"
          )
          );

$perm->check('callsearch');

$export     = $_REQUEST['export'];
$cdr_source = $_REQUEST["cdr_source"];
$trace      = $_REQUEST["trace"];
$action     = $_REQUEST["action"];

require("cdr_generic.php");
require("rating.php");

set_time_limit(1800);

if (!$export) {
    $title="CDRTool call search ";
    if (is_readable("/etc/cdrtool/local/header.phtml")) {
        include("/etc/cdrtool/local/header.phtml");
    } else {
        include("header.phtml");
    }

    if ($_REQUEST['previous_page'] == 'license_page') {

        $db = new DB_CDRTool();

        $query = sprintf("insert into settings (billing_party, var_module,var_name,var_value)
        values ('%s','login','I_agree_with_license','True')",$auth->auth["uname"]);

        $db->query($query);
     }

} else {
    Header("Content-type: text/plain");
    Header("Content-Disposition: inline; filename=cdr.txt");
}

if (isset($CDRTool['dataSourcesAllowed'])) {
    while (list($k,$v)=each($CDRTool['dataSourcesAllowed'])) {
        $cdr_source_els[]=array("label"=>$DATASOURCES[$v]['name'],"value"=>$v);
    }
    if (!$cdr_source) $cdr_source = $cdr_source_els[0]['value'];
}

$CDR_class=$DATASOURCES[$cdr_source]["class"];

if (class_exists($CDR_class)) {
    $CDRS = new $CDR_class($cdr_source);

    if (!$export && !$trace) {
        $layout = new pageLayoutLocal();
        if ($CDRTool['filter']['aNumber']) {
            $layout->showHeader();
            $layout->showTopMenuSubscriber();
        } else {
            $layout->showTopMenu();
        }
    }

    if ($action=='edit' || !$action ) {

        if ($CDRTool['filter']['aNumber']) {
            $CDRS->searchFormSubscriber();
        } else {
            $CDRS->searchForm();
        }
    
    } elseif ($action==search) {
        $CDRS->show();
    }

    if (!$export && !$trace) {
        $layout->showFooter();
    }

} else {
    $log=sprint("Error initializing datasource '%s', class '%s' is not defined",$cdr_source,$CDR_class);
    print "<p>$log";
}

if (!$export && !$trace) {
    print "
    </body>
    </html>
    ";
}

page_close();
?>
