<html> 
<HTML>
<HEAD>
  <TITLE>
    CDRTool on <?
    $SERVER_NAME = $_SERVER["SERVER_NAME"];
    print "\"$SERVER_NAME\"";
    ?>
  </TITLE>
  <META NAME=Description CONTENT=
  "CDR mediation for Voice over IP (SER, Asterisk and Cisco)">
  <META NAME=Keywords CONTENT="SIP Express router, Asterisk, Cisco">
  <LINK REL="SHORTCUT ICON" HREF="images/cdrtool.ico">
  <LINK REL="icon" HREF="images/cdrtool.ico" TYPE="image/ico">
</HEAD>
<frameset rows="90%,*">
<frame name="top" src="callsearch.phtml">
<frame name="bottom" src="blank.phtml">
<noframes>
<body>
<p>This page uses frames, but your browser doesn't support them.</p>
</body>
</noframes>
</frameset>
</html>
