<?
global $CDRTool; 

printf("<HTML>
<HEAD>
  <TITLE>CDRTool - $title</TITLE>
  <LINK REL=\"SHORTCUT ICON\" HREF=\"images/cdrtool.ico\">
  <LINK REL=\"icon\" HREF=\"images/cdrtool.ico\" TYPE=\"image/ico\">
  <SCRIPT language=\"JavaScript1.2\" src=\"main.js\" type=\"text/javascript\"></SCRIPT>
  <link rel=\"stylesheet\" type=\"text/css\" href=\"%s/style.css\">
",$CDRTool['tld']
);

printf ("</HEAD>");
printf ("<body marginwidth=10 leftmargin=10 link=#000066 vlink=#006666>");
?>
