<?
header("Cache-Control: no-cache, must-revalidate");
header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
header("Expires: " . gmdate("D, d M Y H:i:s") . " GMT");
header("ETag: ",randomstring());

global $CDRTool; 

print "<!DOCTYPE html>\n";

printf("<HTML>
<HEAD>
  <TITLE>CDRTool - $title</TITLE>
  <META NAME=Description CONTENT=
  \"CDR mediation and rating engine for OpenSIPS\">
  <META NAME=Keywords CONTENT=\"OpenSIPS, Asterisk, SIP Express router, Cisco\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
  <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"images/favicons/apple-touch-icon-57x57.png\">
  <link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"images/favicons/apple-touch-icon-60x60.png\">
  <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"images/favicons/apple-touch-icon-72x72.png\">
  <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"images/favicons/apple-touch-icon-76x76.png\">
  <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"images/favicons/apple-touch-icon-114x114.png\">
  <link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"images/favicons/apple-touch-icon-120x120.png\">
  <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"images/favicons/apple-touch-icon-144x144.png\">
  <link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"images/favicons/apple-touch-icon-152x152.png\">
  <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"images/favicons/apple-touch-icon-180x180.png\">
  <link rel=\"icon\" type=\"image/png\" href=\"images/favicons/favicon-32x32.png\" sizes=\"32x32\">
  <link rel=\"icon\" type=\"image/png\" href=\"images/favicons/favicon-194x194.png\" sizes=\"194x194\">
  <link rel=\"icon\" type=\"image/png\" href=\"images/favicons/favicon-96x96.png\" sizes=\"96x96\">
  <link rel=\"icon\" type=\"image/png\" href=\"images/favicons/android-chrome-192x192.png\" sizes=\"192x192\">
  <link rel=\"icon\" type=\"image/png\" href=\"images/favicons/favicon-16x16.png\" sizes=\"16x16\">
  <link rel=\"manifest\" href=\"images/favicons/manifest.json\">
  <link rel=\"mask-icon\" href=\"images/favicons/safari-pinned-tab.svg\" color=\"#5670d4\">
  <meta name=\"msapplication-TileColor\" content=\"#2d89ef\">
  <meta name=\"msapplication-TileImage\" content=\"images/favicons/mstile-144x144.png\">
  <meta name=\"theme-color\" content=\"#5670d4\">
  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/> 
  <SCRIPT language=\"JavaScript1.2\" src=\"main.js\" type=\"text/javascript\"></SCRIPT>
  <link href=\"bootstrap/css/bootstrap.css\" rel=\"stylesheet\">
  <link href=\"bootstrap/css/bootstrap-responsive.css\" rel=\"stylesheet\">
  <link rel=\"stylesheet\" type=\"text/css\" href=\"%s/style.css\">
",$CDRTool['tld']);

if (isset($refreshURL)) {
    if (!$refreshTime) $refreshTime=0;
    printf ("<meta http-equiv='Refresh' content='%s; URL=%s'>",$refreshTime,$refreshURL);
}

printf ("</HEAD>
<body data-offset=\"50\" data-spy=\"scroll\" background=\"images/gradient_texture.png\" >
");
?>

    <script src="bootstrap/js-used/jquery.js"></script>
    <script src="bootstrap/js-used/bootstrap-transition.js"></script>
    <script src="bootstrap/js-used/bootstrap-scrollspy.js"></script>
    <script src="bootstrap/js-used/bootstrap-tooltip.js"></script>
    <script src="bootstrap/js-used/bootstrap-popover.js"></script>
    <script src="bootstrap/js-used/bootstrap-dropdown.js"></script>
    <script src="bootstrap/js-used/bootstrap-collapse.js"></script>
    <script src="bootstrap/js-used/bootstrap-button.js"></script>
    <script src="bootstrap/js-used/bootstrap-fileupload.js"></script>
    <script src="bootstrap/js-used/application.js"></script>

<DIV id="TipLayer" style="visibility:hidden;position:absolute;z-index:1000;top:-100"></DIV>
<SCRIPT language="JavaScript1.2" src="style.js" type="text/javascript"></SCRIPT>
<SCRIPT>
    function toggleVisibility(rowid) {
        if (document.getElementById) {
            row = document.getElementById(rowid);
            if (row.style.display == "table-row") {
                row.style.display = "none";
            } else {
                row.style.display = "table-row";
            }
            return false;
        } else {
            return true;
        }
    }

</SCRIPT>
