<?
print "<HTML>
<HEAD>
  <TITLE>CDRTool - $title</TITLE>
  <META NAME=Description CONTENT=
  \"CDR mediation for Voice over IP (SER, Asterisk and Cisco)\">
  <META NAME=Keywords CONTENT=\"Asterisk, SIP Express router, Cisco\">
  <LINK REL=\"SHORTCUT ICON\" HREF=\"images/cdrtool.ico\">
  <LINK REL=\"icon\" HREF=\"images/cdrtool.ico\" TYPE=\"image/ico\">
  <SCRIPT language=\"JavaScript1.2\" src=\"main.js\" type=\"text/javascript\"></SCRIPT>
</HEAD>
<body marginwidth=10 leftmargin=10 link=#000066 vlink=#006666 text=black background=\"images/macbg.gif\">
";
?>
<style type="text/css">
<!--
.border         { border: 1px solid #cccccc; border-collapse: collapse;}
h1              { font-family: Verdana, Arial, Helvetica, sans-serif; font-size:14pt; }
h2              { font-family: Verdana, Arial, Helvetica, sans-serif; font-size:12pt; }
h3              { font-family: Verdana, Arial, Helvetica, sans-serif; font-size:10pt; }
p               { font-family: Verdana, Arial, Helvetica, sans-serif; font-size:8pt; }
pre             { font-family: Lucida Console, Courier New, Courier; font-size: 8pt; }
ul              { font-family: Verdana, Arial, Helvetica, sans-serif; font-size:8pt;  }
li              { font-family: Verdana, Arial, Helvetica, sans-serif; font-size:8pt;  }
div             { font-family: Verdana, Arial, Helvetica, sans-serif }
center          { font-family: Verdana, Arial, Helvetica, sans-serif }
input 		    { font-family: Verdana, Arial, Helvetica, sans-serif ; font-size:8pt; }
textarea   	    { font-family: Verdana, Arial, Helvetica, sans-serif ; font-size:8pt; }
select		    { font-family: Verdana, Arial, Helvetica, sans-serif ; font-size:8pt; }
submit		    { font-family: Verdana, Arial, Helvetica, sans-serif ; font-size:8pt; }
td              { font-family: Verdana, Arial, Helvetica, sans-serif ;  font-size:8pt; }
th              { font-family: Verdana, Arial, Helvetica, sans-serif ; font-size:10pt; }
div.box         { border: solid; border-width: thin; width: 100%; align: center; color: #000000 }

-->
</style>

<style type="text/css">
<!--

.extrainfo {
   display: none;
   font-family: Verdana, Arial, Helvetica, sans-serif;
   font-size: 7pt;
   color: black;
}

-->
</style>

<DIV id="TipLayer" style="visibility:hidden;position:absolute;z-index:1000;top:-100"></DIV>
<SCRIPT language="JavaScript1.2" src="style.js" type="text/javascript"></SCRIPT>
<SCRIPT>
    function toggleVisibility(rowid) {
        if (document.getElementById) {
            row = document.getElementById(rowid);
            if (row.style.display == "block") {
                row.style.display = "none";
            } else {
                row.style.display = "block";
            }
            return false;
        } else {
            return true;
        }
    }

</SCRIPT>
