<?
$errorReporting = (E_ALL & ~E_NOTICE);
$errorReporting = 1;    // comment this out to enable PHP warnings
error_reporting($errorReporting);

include("/etc/cdrtool/global.inc");

if ($DATASOURCES) {
    page_open(array(
             "sess" => "CDRTool_Session",
             "auth" => "CDRTool_Auth",
             "perm" => "CDRTool_Perm")
             );
    $loginname=$auth->auth["uname"];

    $title="Legal notice";

    $db = new DB_CDRTool();
    $query=sprintf("select * from settings
    where billing_party = '%s'
    and var_module= 'login'
    and var_name = 'I_agree_with_license'",$loginname);
    if ($db->query($query)) {
    	if ($db->num_rows()) {
        	$refreshURL='callsearch.phtml';
        	$refreshTime=0;
        }
    }

	if (is_readable("/etc/cdrtool/local/header.phtml")) {
		include_once("/etc/cdrtool/local/header.phtml");
	} else {
		include_once("header.phtml");
	}

    $layout = new pageLayoutLocal();
    $layout->showHeader();
    $layout->showLegalNotice();
    $layout->showFooter();
    page_close();

} else {
    $Setup = new SETUP ();
    $Setup->showIntro();
}

class SETUP {
    function showIntro() {
        print "
        <html>
        <head>
        <title>CDRTool setup</title>
        </head>
        <body>
        <h2>CDRTool setup</h2>
        CDRTool has not been setup on this machine yet.
        <p>

	You must first setup php, apache and to create the cdrtool database.
	Detailed installation instructions are available in <a href=doc/INSTALL.txt>doc/INSTALL.txt</a>

        <p>
        Once the database is available, create the cdrtool configuration
        file by copying the sample configuration file:
        <p>
        cp setup/global.inc.simple.sample /etc/cdrtool/global.inc
        <p>
        Then edit the configuration file global.inc to reflect your platform setup.
        This is the content of the current sample configuration file:
        ";

        print "<pre>";
        $fp=fopen("setup/global.inc.simple.sample",r);
        while ($buffer = fgets($fp,1024)) {
            if (!preg_match("/(<\?)|(\?>)/",$buffer)) {
                print "$buffer";
            }
        }
        print "</pre>";
    }
}

print "
</body>
</html>
";
?>
