<?
include("./global.inc");
page_open(
    array("sess" => "CDRTool_Session",
          "auth" => "CDRTool_Auth",
          "perm" => "CDRTool_Perm"));

$loginname=$auth->auth["uname"];

$title           = "Logs";
$cdr             = new DB_CDRTool;
$search_text     = $_REQUEST['search_text'];
$task            = $_REQUEST['task'];
$current_log     = $_REQUEST['current_log'];
$log_description = $_REQUEST['log_description'];
$next            = $_REQUEST['next'];
$maxrowsperpage  = 20;
$PHP_SELF        = $_SERVER['PHP_SELF'];

if (is_readable("local/header.phtml")) {
	include("local/header.phtml");
} else {
	include("header.phtml");
}

if ($search_text) {
	$search_text=preg_replace("/[^\d|\w| -\.@_]/s","",$search_text);
}

print "<center>";

$layout = new pageLayoutLocal();
$layout->showTopMenu($title);

print "
<form method=post>
<p>Search history of the queries
<font size=-2>
<input type=text name=search_text value=\"$search_text\">
<input type=submit value=Search>
</font>
</form>
</center>
";

if ($perm->have_perm(admin)) {
	$query="select * from auth_user where perms like '%admin%'";
    dprint($query);
    $cdr->query($query);
    while ($cdr->next_record()) {
    	$Collegues[$cdr->f('email')] =$cdr->f('name');
        if ($loginname == $cdr->f('username')) {
            $myEmailAddress=$cdr->f('email');
            $myName=$cdr->f('name');
        }
    }
} else {
	$Collegues[$CDRTool['provider']['toEmail']] = $CDRTool['provider']['name'];
    $myName	=$CDRTool["loginName"];
    $myEmailAddress=$CDRTool["loginEmail"];
}

if ($current_log ) {
    if ($task == "edit") {
    
        $query=sprintf("update log set description = '%s' where id = %d",
        addslashes($log_description),$current_log);

		if (!$perm->have_perm("admin")) {
    		$query.=sprintf(" and login = '%s' ",addslashes($auth->auth["uname"]));
		}

        dprint($query);
        $cdr->query($query);

    } else if ($task == "mailLog" && $recipient) {
        $query=sprintf("select * from log where id = %d",$current_log);

        if (!$perm->have_perm("admin")) {
    		$query.=sprintf(" and login = '%s' ",addslashes($auth->auth["uname"]));
		}

        dprint($query);
        $cdr->query($query);
        $cdr->next_record();
        $rerun         	=$cdr->f('rerun');
	    $description    =$cdr->f('description');

        if ($_SERVER['HTTPS']=="on") {
            $protocolURL="https://";
        } else {
            $protocolURL="http://";
        }

		$subject="CDRTool";

        $fullURL=$protocolURL.$_SERVER['HTTP_HOST'].$CDRTool['tld']."/".$rerun;
        $body="CDRTool query to analize:\n\n$fullURL\n\n";
        if ($description) {
            $body=$body."The query id $current_log is saved with name \"$description\"\n\n";
			$subject=$subject.": ".$description;
        }

        $body=$body."This notification has been sent to you from CDRTool log interface by $myName";

        mail($recipient,$subject,$body,"From: $myEmailAddress");
        print "<p>Notified $recipient.";
    }
}

$where = " (1=1) ";

if (!$perm->have_perm("admin")) {
    $where.=sprintf(" and login = '%s'",addslashes($auth->auth["uname"]));
}

if ($search_text) {
    $where.=sprintf(" and (description like '%s%s%s' or url like '%s' or id = '%s')",
    "%",$search_text,"%",$search_text,$search_text);
    $search_text_enc=urlencode($search_text);
    $url_log=$url_log."&search_text=$search_text_enc";
}

$query = "select count(*) as records from log where ". $where;

dprint($query);

if ($cdr->query($query)) {
    $cdr->next_record();
    $rows = $cdr->f('records');
} else {
    $rows = 0;
}

if (!$next) {
    $i=0;
    $next=0;
} else {
	$i=$next;
}
$j=0;
$z=0;

if  ($rows>0)  {
    if ($rows  >  $maxrowsperpage)  {
        $maxrows=$maxrowsperpage+$next;
        if  ($maxrows  >  $rows)  {
            $maxrows=$rows;
            $prev_rows=$maxrows;
        }
    } else {
        $maxrows=$rows;
    }

    $query = "select * from log where ".
    $where. " order by id desc limit $i,$maxrowsperpage";

    dprint($query);
    
    $cdr->query($query);

    print "<center><p>Found $rows records. </center>
           <table class=border cellspacing=1 width=100% align=center>
           <tr bgcolor=lightgrey>
           <td class=cdr> </td>
           <td class=cdr> <b>Id</td>
           <td class=cdr> <b>Date/time</td>
           <td class=cdr> <b>Login</td>
           <td class=cdr> <b>Datasource</td>
           <td class=cdr> <b>From</td>
           <td class=cdr> <b>Run</td>
           <td class=cdr> <b>Edit</td>
           <td class=cdr> <b>Res</td>
           <td class=cdr> <b>Description  </td>
           <td class=cdr> <b>Notify</td>
           </tr>
	";

	while  ($i<$maxrows)  {
            
        $found=$i+1;
        $cdr->next_record();											

        $current_log    =$cdr->f('id');
       	$log_date		=$cdr->f('date');
       	$login		    =$cdr->f('login');
       	$ip	         	=$cdr->f('ip');
       	$url         	=$cdr->f('url');
        $reedit         =$cdr->f('reedit');
        $rerun         	=$cdr->f('rerun');
       	$results        =$cdr->f('results');
	    $description    =$cdr->f('description');
        $datasource     =$cdr->f('datasource');

        if (!$reedit || !$rerun) {
            if (preg_match("/do_search/", $url)) {
                $url_run="<a href=\"../search_call/$url"."&history_id=$current_log"."\">Run</a>";
                $url_edit=preg_replace("/do_/","",$url);
                $url_edit="<a href=\"../search_call/$url_edit\">Edit</a>";
                $display_form=1;
            } elseif (preg_match("/do_statistics/", $url)) {
                $url_run="<a href=\"../statistics/$url"."&history_id=$current_log"."\">Run</a>";
                $url_edit=preg_replace("/do_/","",$url);
                $url_edit="<a href=\"../statistics/$url_edit\">Edit stat</a>";
                $display_form=1;
            } else {
                $url_edit="-";
                $url_run="-";
                $display_form=0;
            }
        } else {
            $display_form=1;
        	$url_run="<a href=\"$rerun\">Run</a>";
            $url_edit="<a href=\"$reedit\">Edit</a>";
        }

        $rr=floor($found/2);
        $mod=$found-$rr*2;
    
        if ($mod ==0) {
            $bgcolor="lightgrey";
        } else {
            $bgcolor="white";
        }

    	print  "
		<tr bgcolor = $bgcolor>
		<td class=cdr><b>$found.</b></td>
		<td class=cdr>$current_log</td>
        <td class=cdr>$log_date</td>
		<td class=cdr>$login</td>
        <td class=cdr>$datasource</td>
		<td class=cdr>$ip</td>
		<td class=cdr>$url_run</td> 
		<td class=cdr>$url_edit</td>
		<td class=cdr>$results</td>
		<td class=cdr>
		";

		if ($display_form == 1) {
            print "
            <form method=post>
            <input type=text size=30 name=log_description value=\"$description\">
            <input type=hidden name=current_log value=\"$current_log\">
            <input type=hidden name=task value=edit>
            <input type=hidden name=next value=$next>
            <input type=hidden name=search_text value=\"$search_text\">
            <input type=submit value=Save>
            </td>
			</form>
            <td class=cdr valign=center>
            <form method=post>
            <select name=recipient>
            ";
                foreach(array_keys($Collegues) as $col) {
                    print "<option value=\"$col\">$Collegues[$col]";
                }

            print "
            </select>
            <input type=hidden name=current_log value=\"$current_log\">
            <input type=hidden name=task value=mailLog>
            <input type=hidden name=next value=$next>
            <input type=hidden name=search_text value=\"$search_text\">
            <input type=submit value=Mail>
            </td>
			</form>
            <td class=cdr valign=center>

            ";
		} else {
			print "<font color=red>$description</font>";
		}
		print "
		</td>
		</tr>

		";
	    $i++;
	}
	print "</table>
    ";

}

print "
<p>
<center>
<table  border=0>
<tr>
<td>
";

if  ($next!=0  ) {
    $show_next=$maxrowsperpage-$next;
    if  ($show_next < 0)  {
        $mod_show_next  =  $show_next-2*$show_next;
    }
    $url_prev	=$PHP_SELF."?".$url_log."&action=search&next=$mod_show_next";
    print "<a href=\"$url_prev\">Previous</a> ";
}

print "
</td>
<td>
";
if ($rows>$maxrowsperpage && $rows!=$maxrows)  {
    $show_next  =$maxrowsperpage+$next;
    $url_next	=$PHP_SELF."?".$url_log."&action=search&next=$show_next";
    print "<a href=\"$url_next\">Next</a>";
}

print "
</td>
</tr>
</table>
";

$layout->showFooter();

print "
</body>
</html>
";

page_close();
?>
