<?
include("global.inc");

page_open(array(
	"sess" => "CDRTool_Session", 
	"auth" => "CDRTool_Auth",
	"perm" => "CDRTool_Perm"));

$loginname=$auth->auth["uname"];

$auth->logout();
$sess->delete();

$title="Logout";
if (is_readable("local/header.phtml")) {
    include("local/header.phtml");
} else {
    include("header.phtml");
}

$layout = new pageLayoutLocal();
$layout->showLogout($loginname);
$layout->showFooter();

print "
</body>
</html>
";
?>
