<?php
require("/etc/cdrtool/global.inc");

page_open(
    array(
        "sess" => "CDRTool_Session",
        "auth" => "CDRTool_Auth",
        "perm" => "CDRTool_Perm"
    )
);

$title = sprintf("CDRTool media trace for session %s", $callid);
include("header.phtml");
$cdr_source  = $_REQUEST['cdr_source'];

if (in_array($cdr_source,$CDRTool['dataSourcesAllowed'])) {

    $proxyIP     = $_REQUEST['proxyIP'];
    $callid      = $_REQUEST['callid'];
    $fromtag     = $_REQUEST['fromtag'];
    $totag       = $_REQUEST['totag'];

    require("cdr_generic.php");

    $mediaTrace = new Media_trace($cdr_source);
    $mediaTrace->show($proxyIP, $callid, $fromtag, $totag);

} else {
    printf("Error: Invalid datasource '%s' for user '%s'", $cdr_source, $auth->auth["uname"]);
}

print "
</body>
</html>
";
page_close();
?>
