<?php
require("/etc/cdrtool/global.inc");

page_open(
            array("sess" => "CDRTool_Session",
                  "auth" => "CDRTool_Auth",
                  "perm" => "CDRTool_Perm"));

$perm->check("admin");

$title="MySQL replication status";

if (is_readable("/etc/cdrtool/local/header.phtml")) {
    include("/etc/cdrtool/local/header.phtml");
} else {
    include("header.phtml");
}

$layout = new pageLayoutLocal();
$layout->showTopMenu($title);

require("mysql_replication.php");

$ReplicationOverview = new ReplicationOverview($replicated_databases);
$ReplicationOverview->showOverview();
    
$layout->showFooter();

print "
</body>
</html>
";

page_close();
?>
