<?
// This library can be used to display the status of mysql replication of
// arbitrary number of mysql servers and instructions about how to fix
// a broken replication process

/*

To use this library create a web page like this:

$replicated_databases=array(
                 "cluster1" => array("db1"=>array('ip'       => '10.0.0.131',
                                                 'slave_of' => 'db2',
                                                 'user'     => 'root',
                                                 'password' => 'pass'
                                                     ),
                                     "db2"=>array('ip'       => '10.0.0.132',
                                                  'slave_of' => 'db1'
                                                  'user'     => 'root',
                                                  'password' => 'pass'
                                                  )
                                     )
                 );


require("mysql_replication_lib.phtml");

$ReplicationOverview = new ReplicationOverview($clusters);
$ReplicationOverview->showOverview();

*/


class DBx extends DB_Sql {
  function DBx($host='localhost', $user, $password) {
      $this->Host = $host;
      $this->User = $user;
      $this->Password = $password;
      $this->Database = 'mysql';
      parent::DB_Sql();
  }
}

class MySQLReplicationStatus {
	var $slave_status_query="show slave status";
    var $master_status_query="show master status";

    function MySQLReplicationStatus($host,$clusters) {

        $db = new DBx ($clusters[$host]['ip'],$clusters[$host]['user'],$clusters[$host]['password']);

        if (!$db->query($this->slave_status_query)) {
            printf ("<p><font color=red>Error from MySQL server %s: %s (%s) for query: %s</font>",$clusters[$host]['ip'],$db->Error,$db->Errno,$this->slave_status_query);
            return false;
        }

		$db->next_record();

        $this->slave_master         = $db->f('Master_Host');
        $this->slave_user           = $db->f('Master_User');
        $this->slave_master_port    = $db->f('Master_Port');
        $this->slave_log_file	    = $db->f('Master_Log_File');
        $this->slave_position       = $db->f('Read_Master_Log_Pos');
        $this->slave_sql_running	= $db->f('Slave_SQL_Running');
        $this->slave_io_running	    = $db->f('Slave_IO_Running');
        $this->slave_last_errno	    = $db->f('Last_Errno');
        $this->slave_last_error 	= $db->f('Last_Error');
        $this->slave_seconds_behind = $db->f('Seconds_Behind_Master');

        if (!$db->query($this->master_status_query)) {
            printf ("<p><font color=red>MySQL error: %s (%s) for query: %s</font>",$db->Error,$db->Errno,$this->slave_status_query);
            return;
        }

		$db->next_record();

    	$this->master_position	    = $db->f('Position');
    	$this->master_log_file	    = $db->f('File');

    }
}

class ReplicationOverview {
    var $status=array();

    function ReplicationOverview($clusters=array()) {
    	$this->clusters = $clusters;

        $this->cluster = $_REQUEST['cluster'];
        $this->server  = $_REQUEST['server'];

		$cluster_names=array_keys($this->clusters);

        if (!$this->cluster) $this->cluster = $cluster_names[0];

        foreach (array_keys($this->clusters[$this->cluster]) as $key) {
            $this->status[$key]= new MySQLReplicationStatus($key,$this->clusters[$this->cluster]);
        }

        foreach (array_keys($this->clusters[$this->cluster]) as $key) {
            if ($this->server && $key==$this->server) {
                $this->master_hostname=$this->clusters[$this->cluster][$key]['slave_of'];
                $this->master_ip=$this->clusters[$this->cluster][$this->master_hostname]['ip'];
                $this->master=$this->clusters[$this->cluster][$key]['slave_of'];
                break;
            }
        }

        foreach (array_keys($this->clusters[$this->cluster]) as $key) {
        	if ($this->server && $this->clusters[$this->cluster][$key]['slave_of'] == $this->master && $key != $this->server) {
                $this->slave_ip=$this->clusters[$this->cluster][$key]['ip'];
                $this->slave_hostname =$key;
                break;
            }
        }
    }

    function showOverview() {

        print "<p>
        Available MySQL clusters: ";

        foreach (array_keys($this->clusters) as $key) {
            printf (" <a href=%s?cluster=%s>$key</a> ",$_SERVER['PHP_SELF'],$key);
        }
        

        printf ("
        <table border=0>
        <tr>
        <td></td>
        <td colspan=%s class=border align=center><h1>%s</h1></td>
        </tr>
        <tr>
        <th></th>
        ",
        count($this->clusters[$this->cluster]),
        $this->cluster
        );

        foreach (array_keys($this->clusters[$this->cluster]) as $key) {
            printf ("<th class=border>%s (%s)",$key,$this->clusters[$this->cluster][$key]['ip']);
            if ($this->server != $key) {
            	printf ("<br><a href=%s?server=%s&cluster=%s>Click to learn how to repair me</a></th>",$_SERVER['PHP_SELF'],urlencode($key),urlencode($this->cluster));
            }
        }
        
        print "</tr>
        ";

        print "<tr>
        <td></td>";
        
        foreach (array_keys($this->clusters[$this->cluster]) as $key) {
            print "<td class=border valign=top>";
        
            print "
            <table>
            <tr>
            <td>Slave status</td><td>Master status</td></tr>
            ";
            print "<tr>";
            print "
            <td valign=top>
            ";
        
            if ($this->status[$key]->slave_sql_running == 'No') {
                $sql_color="red";
            } else {
                $sql_color="white";
            }
        
            if ($this->status[$key]->slave_io_running == 'No') {
                $io_color="red";
            } else {
                $io_color="white";
            }
        
            print "<table border=1>";
            printf ("<tr><td class=border>Master host</td><td>%s</td></tr>",$this->status[$key]->slave_master);
            printf ("<tr><td class=border>Master port</td><td>%s</td></tr>",$this->status[$key]->slave_master_port);
            printf ("<tr><td class=border>Log file</td><td>%s</td></tr>",$this->status[$key]->slave_log_file);
            printf ("<tr><td class=border>Position</td><td>%s</td></tr>",$this->status[$key]->slave_position);
            printf ("<tr><td class=border>SQL thread</td><td bgcolor=%s>%s</td></tr>",$sql_color,$this->status[$key]->slave_sql_running);
            printf ("<tr><td class=border>IO thread</td><td bgcolor=%s>%s</td></tr>",$io_color,$this->status[$key]->slave_io_running);
            printf ("<tr><td class=border>Delay</td><td>%s</td></tr>",$this->status[$key]->slave_seconds_behind);
            printf ("<tr><td class=border>Last error</td><td>%s</td></tr>",$this->status[$key]->slave_last_error);
            printf ("<tr><td class=border>Last errno</td><td>%s</td></tr>",$this->status[$key]->slave_last_errno);
            print "</table>";
            print "
            </td>
            ";
        
            print "
            <td valign=top>
            ";
            print "<table border=1>";
            printf ("<tr><td class=border>Log file</td><td>%s</td></tr>",$this->status[$key]->master_log_file);
            printf ("<tr><td class=border>Position</td><td>%s</td></tr>",$this->status[$key]->master_position);
            print "</table>";
        
            print "
            </td>
            </table>
            ";
        
            print "</td>";
        }
        
        print "</tr>";

 		$this->printInstructions();

        print "
        </table>
        ";
 }

    function printStep ($hostname,$instructions='',$downtime=false) {
        $this->step++;
        print "<tr>
        <td>$this->step
        </td>";

        foreach (array_keys($this->clusters[$this->cluster]) as $key) {
            if ($downtime && $key==$this->master_hostname) {
                $bgcolor="red";
            } else {
                $bgcolor="white";
            }
            if ($key==$hostname) {
                print "<td class=border bgcolor=$bgcolor><pre>$instructions</pre></td>";
            } else {
            	if ($downtime && $key==$this->master_hostname) {
                	print "<td class=border bgcolor=$bgcolor valign=middle align=center><b><font color=white>Downtime</font></b></td>";
                } else {
                	print "<td class=border></td>";
                }
            }
        }
        print "</tr>";

    }

    function printInstructions() {

    if (!$this->server) return;


$text="The ssh public keys for user root must be shared <br>between machines. Test scp as root between machines.";

$this->printStep($this->master_hostname,$text);

if ($this->slave_hostname) {

$text=sprintf("
mysql -u root -p

flush tables with read lock;

show master status;

# write down the file and possition %s.file %s.pos
<font color=red># do not exit the mysql console</font>

",$this->master_hostname,$this->master_hostname);

$this->printStep($this->master_hostname,$text);

$text=sprintf("

mysql -u root -p

show slave status;
# wait until same file/pos as %s is displayed)

slave stop;
",$this->master_hostname);

$this->printStep($this->slave_hostname,$text,true);

$text="unlock tables;";

$this->printStep($this->master_hostname,$text);


$text="

/etc/init.d/monit stop

/etc/init.d/mysql stop

";

$this->printStep($this->slave_hostname,$text);

$text="

/etc/init.d/monit stop

/etc/init.d/mysql stop

";

$this->printStep($this->server,$text);

$text=sprintf("
rsync -avzP --delete /var/lib/mysql %s:/var/lib/

/etc/init.d/mysql start

/etc/init.d/monit start
",$this->server);

$this->printStep($this->slave_hostname,$text);


$text=sprintf("
(cd /var/lib/mysql/; rm *.info *relay-bin*)

/etc/init.d/mysql start

/etc/init.d/monit start

mysql -u root -p

show master status;
# write down the file and possition %s.file %s.pos

CHANGE MASTER TO MASTER_HOST='%s',
MASTER_USER='%s',
MASTER_PASSWORD='%s',
MASTER_LOG_FILE='%s.file',
MASTER_LOG_POS=%s.pos;

slave start;

",$this->server,
$this->server,
$this->master_ip,
$this->clusters[$this->cluster][$this->master_hostname]['replication_user'],
$this->clusters[$this->cluster][$this->master_hostname]['replication_password'],
$this->master_hostname,
$this->master_hostname
);
$this->printStep($this->server,$text);

$text=sprintf("

mysql -u root -p

stop slave;

CHANGE MASTER TO MASTER_HOST='%s',
MASTER_USER='%s',
MASTER_PASSWORD='%s',
MASTER_LOG_FILE='%s.file',
MASTER_LOG_POS=%s.pos;

slave start;
",
$this->clusters[$this->cluster][$this->server]['ip'],
$this->clusters[$this->cluster][$this->server]['replication_user'],
$this->clusters[$this->cluster][$this->server]['replication_password'],
$this->server,
$this->server
);

$this->printStep($this->master_hostname,$text);

    } else {


$text="

/etc/init.d/monit stop

/etc/init.d/mysql stop

";

$this->printStep($this->server,$text);


$text=sprintf("

mysql -u root -p

flush tables with read lock;

show master status;
# write down the file and possition %s.file %s.pos

unlock tables;

/etc/init.d/monit stop

/etc/init.d/mysql stop

rsync -avzP --delete /var/lib/mysql %s:/var/lib/

/etc/init.d/mysql start

/etc/init.d/monit start

",
$this->master_hostname,
$this->master_hostname,
$this->server
);

$this->printStep($this->master_hostname,$text,true);

$text=sprintf("
(cd /var/lib/mysql/; rm *.info *relay-bin*)

/etc/init.d/mysql start

/etc/init.d/monit start

mysql -u root -p

show master status;
# write down the file and possition %s.file %s.pos

CHANGE MASTER TO MASTER_HOST='%s',
MASTER_USER='%s',
MASTER_PASSWORD='%s',
MASTER_LOG_FILE='%s.file',
MASTER_LOG_POS=%s.pos;

slave start;

",$this->server,
$this->server,
$this->master_ip,
$this->clusters[$this->cluster][$this->master_hostname]['replication_user'],
$this->clusters[$this->cluster][$this->master_hostname]['replication_password'],
$this->master_hostname,
$this->master_hostname
);
$this->printStep($this->server,$text);

$text=sprintf("

mysql -u root -p

stop slave;

CHANGE MASTER TO MASTER_HOST='%s',
MASTER_USER='%s',
MASTER_PASSWORD='%s',
MASTER_LOG_FILE='%s.file',
MASTER_LOG_POS=%s.pos;

slave start;
",
$this->clusters[$this->cluster][$this->server]['ip'],
$this->clusters[$this->cluster][$this->server]['replication_user'],
$this->clusters[$this->cluster][$this->server]['replication_password'],
$this->server,
$this->server
);

$this->printStep($this->master_hostname,$text);

    }
}
}
?>
