<?
require("/etc/cdrtool/global.inc");
page_open(
    array("sess" => "CDRTool_Session",
          "auth" => "CDRTool_Auth",
          "perm" => "CDRTool_Perm"
          ));

require("sip_statistics.php");
require("media_sessions.php");
$perm->check("statistics");

$title="SIP network status";
include("header.phtml");

global $CDRTool;
if (strlen($CDRTool['filter']['domain'])) $allowedDomains=explode(' ',$CDRTool['filter']['domain']);

$layout = new pageLayoutLocal();
$layout->showTopMenu($title);

foreach (array_keys($DATASOURCES) as $datasource) {

    print "<div class='row-fluid'>";
    if (in_array($datasource,$CDRTool['dataSourcesAllowed']) && !$DATASOURCES[$datasource]['invisible']) {
        print "<div class='span6'>";

        if ($DATASOURCES[$datasource]['networkStatus']) {
	      	printf ("<h2>%s</h2>",$DATASOURCES[$datasource]['name']);
            printf ("<img src=images/SipThorNetwork.php?engine=%s align=left>",
            $DATASOURCES[$datasource]['networkStatus']);

        } else if ($DATASOURCES[$datasource]['db_registrar']){
	      	printf ("<h2>%s</h2>",$DATASOURCES[$datasource]['name']);
			require_once("cdr_generic.php");
			$online = new SIPonline($datasource,$DATASOURCES[$datasource]['db_registrar']);
            $online->showAll();
        }

        print "</div>";
        print "<div class='span6'>";

        if ($DATASOURCES[$datasource]['mediaSessions']) {
           	$MediaSessions = new MediaSessionsNGNPro($DATASOURCES[$datasource]['mediaSessions'],$allowedDomains);
            $MediaSessions->getSessions();
            $MediaSessions->getSummary();
            print "<div class=row><h2>Media relays</h2></div>";
            $MediaSessions->showSummary();

        } else if ($DATASOURCES[$datasource]['mediaDispatcher']) {
           	$MediaSessions = new MediaSessions($DATASOURCES[$datasource]['mediaDispatcher'],$allowedDomains);
            $MediaSessions->getSessions();
            $MediaSessions->getSummary();
            print "<div class=row><h2>Media relays</h2></div>";
            $MediaSessions->showSummary();
        }

        if ($DATASOURCES[$datasource]['networkStatus']) {
        	$NetworkStatistics = new NetworkStatistics($DATASOURCES[$datasource]['networkStatus'],$allowedDomains);
            print "<div class=row><h2>SIP accounts</h2></div>";
            $NetworkStatistics->showStatistics();
            print "<div class=row><h2>Network topology</h2></div>";
            $NetworkStatistics->showStatus();
        }

        print "</div>";
    }
    print "</div>";
}


$layout->showFooter();

print "
</body>
</html>
";
page_close();

?>
