<?
include("./global.inc");
page_open(
            array("sess" => "CDRTool_Session",
                  "auth" => "CDRTool_Auth",
                  "perm" => "CDRTool_Perm"));

$title="Provisioning interface";

if (is_readable("local/header.phtml")) {
    include("local/header.phtml");
} else {
    include("header.phtml");
}

set_time_limit(600);
//$perm->check("admin");

require_once("provisioning/provisioning_soap_library.phtml");
require_once("provisioning/provisioning_logic.phtml");

$layout = new pageLayoutLocal();
$layout->showTopMenu();

// $soapEngines must be defined in global.inc

global $CDRTool;

if ($CDRTool['reseller']) {
	$loginCredentials=array(
                        'reseller'           => $CDRTool['reseller'],
                        'loginType'          => 'reseller'
                        );
} else {
	$loginCredentials=array(
                        'loginType'          => 'admin'
                        );
}

$extraFormElements=array();

if ($_REQUEST['generatorId']) {
    $generator  = new recordGenerator($_REQUEST['generatorId'],$recordGenerators,$soapEngines,$extraFormElements,$loginCredentials);
    if ($_REQUEST['action']=='Generate') {
        $generator->generateRecords();
        $generator->showGeneratorForm();
    } else {
        $generator->showGeneratorForm();
    }
} else {
	$SOAPEngine = new SOAPEngine($_REQUEST['service'],$soapEngines,$extraFormElements,$loginCredentials);
    $_class     = $SOAPEngine->recordsClass;
    $RECORDS    = new $_class(&$SOAPEngine);
    
    if ($_REQUEST['action']=='Add')    $RECORDS->addRecord();
    if ($_REQUEST['action']=='Delete') $RECORDS->deleteRecord();
    if ($_REQUEST['action']=='PerformActions') {
        $RECORDS->performActions();
    } else {
        $RECORDS->listRecords();
    }
    
}
$layout->showFooter();

print "
</body>
</html>
";

page_close();
?>