<?
include("./global.inc");
page_open(
            array("sess" => "CDRTool_Session",
                  "auth" => "CDRTool_Auth",
                  "perm" => "CDRTool_Perm"));

$title="Provisioning interface";

if (is_readable("local/header.phtml")) {
    include("local/header.phtml");
} else {
    include("header.phtml");
}

set_time_limit(600);
//$perm->check("admin");

require_once("provisioning_soap_library.phtml");
require_once("provisioning_logic.phtml");

$layout = new pageLayoutLocal();
$layout->showTopMenu();

// $soapEngines must be defined in global.inc

global $CDRTool;

if ($_REQUEST['generatorId']) {
	if ($CDRTool['reseller']) {
    	$generator  = new recordGenerator($_REQUEST['generatorId'],$recordGenerators,$soapEngines,,$CDRTool['reseller'],1);
	} else {
    	$generator  = new recordGenerator($_REQUEST['generatorId'],$recordGenerators,$soapEngines,,,1);
		$SOAPEngine = new SOAPEngine($_REQUEST['service'],$soapEngines,,,1);
	}
    if ($_REQUEST['action']=='Generate') {
        $generator->generateRecords();
        $generator->showGeneratorForm();
    } else {
        $generator->showGeneratorForm();
    }
} else {
	if ($CDRTool['reseller']) {
		$SOAPEngine = new SOAPEngine($_REQUEST['service'],$soapEngines,,$CDRTool['reseller'],0);
	} else {
		$SOAPEngine = new SOAPEngine($_REQUEST['service'],$soapEngines,,,1);
	}

    $_class     = $SOAPEngine->recordsClass;
    $RECORDS    = new $_class(&$SOAPEngine);
    
    if ($_REQUEST['action']=='Add')    $RECORDS->addRecord();
    if ($_REQUEST['action']=='Delete') $RECORDS->deleteRecord();
    if ($_REQUEST['action']=='PerformActions') {
        $RECORDS->performActions();
    } else {
        $RECORDS->listRecords();
    }
    
}
$_class     = $SOAPEngine->recordsClass;
$RECORDS    = new $_class(&$SOAPEngine);

if ($_REQUEST['action']=='Add') $RECORDS->addRecord();
if ($_REQUEST['action']=='Delete') $RECORDS->deleteRecord();
if ($_REQUEST['action']=='PerformActions') {
	$RECORDS->performActions();
} else {
	$RECORDS->listRecords();
}
$layout->showFooter();

print "
</body>
</html>
";

page_close();
?>