<?
require("/etc/cdrtool/global.inc");

page_open(
            array("sess" => "CDRTool_Session",
                  "auth" => "CDRTool_Auth",
                  "perm" => "CDRTool_Perm"));

$perm->check("rates");
include("rating.php");

if ($perm->have_perm("readonly")) {
	$RatingTables=new RatingTables('readonly');
} else {
	$RatingTables=new RatingTables();
}

if (!$_REQUEST['export']) {
    $title="Rating tables";
    if (is_readable("/etc/cdrtool/local/header.phtml")) {
        include("/etc/cdrtool/local/header.phtml");
    } else {
        include("header.phtml");
    }
	$layout = new pageLayoutLocal();
	$layout->showTopMenu($title);

} else {
    Header("Content-type: text/plain");
    $h=sprintf("Content-Disposition: inline; filename=%s",$RatingTables->table_to_csv_name[$_REQUEST['table']]);
    Header($h);
}

if ($_REQUEST['import'] && $_REQUEST['table']) {
	$RatingTables->importTable($_REQUEST['table']);
}

$RatingTables->updateTable();
$RatingTables->showTable();

if (!$_REQUEST['export']) {
	$layout->showFooter();
    print "
    </body>
    </html>
    ";
}

page_close();
?>