<?
include("global.inc");

$errorReporting = (E_ALL & ~(E_NOTICE | E_WARNING));
//$errorReporting = 1; // temporary until warnings are fixed
error_reporting($errorReporting);

if ($_REQUEST['public']) {
    $db = new DB_CDRTool;
    $key="callid-".trim($_REQUEST['callid']).trim($_REQUEST['fromtag']);
    $query=sprintf("select * from memcache where `key` = '%s'",addslashes($key));
    sleep(1);
    dprint($query);
    if ($db->query($query)) {
	    if ($db->num_rows()) {
    	    $authorize=0;
    	} else {
        	$authorize=1;
	    }
    } else {
		$authorize=1;
    }
} else {
	$authorize=1;
}
//print "debug" ;

if ($authorize==1) {
	page_open(array(
          "sess" => "CDRTool_Session",
          "auth" => "CDRTool_Auth",
          "perm" => "CDRTool_Perm")
          );

} else {
	unset($auth);
	unset($sess);
	unset($perm);
}

$verbose=1;
require("cdrlib.phtml");
$callid      = $_REQUEST['callid'];
$fromtag     = $_REQUEST['fromtag'];
$proxyIP     = $_REQUEST['proxyIP'];
$cdr_source  = $_REQUEST['cdr_source'];

if (!$authorize || in_array($cdr_source,$CDRTool['dataSourcesAllowed'])) {

    $title="CDRTool SIP trace: session $callid $method $status";
    include("header.phtml");
    
    $sipTrace = new SIP_trace($cdr_source);
    $sipTrace->show($callid,$fromtag,$proxyIP);

} else {
    printf ("Error: Invalid datasource '%s' for user '%s'" ,$cdr_source,$auth->auth["uname"]);
}

print "
</body>
</html>
";
if ($authorize=1) {
	page_close();
}
?>
