<?
include("global.inc");

#$verbose=1;
    
if ($_REQUEST['public']) {
    $db = new DB_CDRTool;
    $key="callid-".trim($_REQUEST['callid']).trim($_REQUEST['fromtag']);
    $query=sprintf("select * from memcache where `key` = '%s'",addslashes($key));
    sleep(1);
    dprint($query);
    if ($db->query($query)) {
	    if ($db->num_rows()) {
    	    $authorize=0;
    	} else {
        	$authorize=1;
	    }
    } else {
		$authorize=1;
    }
} else {
	$authorize=1;
}

if ($authorize==1) {
	page_open(array(
          "sess" => "CDRTool_Session",
          "auth" => "CDRTool_Auth",
          "perm" => "CDRTool_Perm")
          );

} else {
	unset($auth);
	unset($sess);
	unset($perm);
}

include("header.phtml");
require("cdrlib.phtml");


$proxyIP     = $_REQUEST['proxyIP'];
$callid      = $_REQUEST['callid'];
$fromtag     = $_REQUEST['fromtag'];
$totag       = $_REQUEST['totag'];
$cdr_source  = $_REQUEST['cdr_source'];

if (!$authorize || in_array($cdr_source,$CDRTool['dataSourcesAllowed'])) {

    $title=sprintf("SIP session %s",$callid);
    $sipTrace = new SIP_trace($cdr_source);
    $sipTrace->show($proxyIP,$callid,$fromtag,$totag);

} else {
    printf ("Error: Invalid datasource '%s' for user '%s'" ,$cdr_source,$auth->auth["uname"]);
}

print "
</body>
</html>
";
if ($authorize=1) {
	page_close();
}
?>
