<?
include("global.inc");

if ($_REQUEST['public']) {
    $db = new DB_CDRTool;
    $key="callid-".trim($callid).trim($fromtag);
    $query=sprintf("select * from memcache where `key` = '%s'",addslashes($key));
    sleep(1);
    dprint($query);
    if ($db->query($query)) {
	    if ($db->num_rows()) {
    	    $authorize=0;
    	} else {
        	$authorize=1;
	    }
    } else {
		$authorize=1;
    }
} else {
	$authorize=1;
}

if ($authorize==1) {
	page_open(array(
          "sess" => "CDRTool_Session",
          "auth" => "CDRTool_Auth",
          "perm" => "CDRTool_Perm")
          );

} else {
	unset($auth);
	unset($sess);
	unset($perm);
}

require("cdrlib.phtml");
$callid      = $_REQUEST['callid'];
$method      = $_REQUEST['method'];
$status      = $_REQUEST['status'];
$fromtag     = $_REQUEST['fromtag'];
$cdr_source  = $_REQUEST['cdr_source'];

if (!$authorize || in_array($cdr_source,$CDRTool[dataSourcesAllowed])) {

    $title="CDRTool SIP trace: session $callid $method $status";
    include("header.phtml");
    
    $serTrace = new SER_trace($cdr_source);
    if ($serTrace->initOK) {
        $serTrace->show($callid,$method,$status,$fromtag);
    }
} else {
    printf ("Error: Invalid datasource '%s' for user '%s'" ,$cdr_source,$auth->auth["uname"]);
}

print "
</body>
</html>
";
if ($authorize=1) {
	page_close();
}
?>
