<?php
require '/etc/cdrtool/global.inc';

page_open(
    array(
        "sess" => "SIP_Subscriber_Session",
        "auth" => "SIP_Subscriber_Auth"
    )
);


$loginname = $auth->auth["uname"] ;
$log = sprintf("SIP settings page: %s logged out from %s", $loginname, $_SERVER['REMOTE_ADDR']);
syslog(LOG_NOTICE, $log);

$auth->logout();
$sess->delete();

$title = "Logout";
include 'sip_header.phtml';

print "<h2>";
print _("Login");
print "</h2>";
print "<p>";

print _("You have been logged in as ");
print <<< END
<b>$loginname</b>
    <p class=s>
END;

print _("You have been logged out");
print <<< END
</p>
<br />
<br />
<p>
    <a href="sip_settings.phtml">Login again</a>
</p>
END;

page_close();

print "
</body>
</html>
";
?>
