<?php
/**
 * Copyright (c) 2019 AG Projects
 * http://ag-projects.com
 *
 * This page provides functions for management of
 * SIP account settings on a remote NGNPro server
 *
 */

require("/etc/cdrtool/global.inc");
require("/etc/cdrtool/ngnpro_engines.inc");
require('sip_settings.php');

if ($credentials=getSipAccountFromHTTPDigest()) {
    $account    = $credentials['account'];
    $sip_engine = $credentials['engine'];
    $reseller   = $credentials['reseller'];
    $customer   = $credentials['customer'];
    $login_type = "subscriber";
} else {
    die('HTP digest Credentials error');
}

if ($CDRTool['sip_settings_class']) {
    $_class=$CDRTool['sip_settings_class'];
} else {
    $_class='SipSettings';
}
$_reseller_class=$_class.$reseller;

if (class_exists($_reseller_class)) {
    $SipSettings_class=$_reseller_class;
} else {
    $SipSettings_class=$_class;
}

$login_credentials = array(
    'reseller'       => $reseller,
    'customer'       => $customer,
    'login_type'     => $login_type,
    'sip_engine'     => $sip_engine,
    'templates_path' => './templates'
);

renderUI($SipSettings_class, $account, $login_credentials, $soapEngines);

?>
