<?
/*
    Copyright (c) 2009 AG Projects
    http://ag-projects.com

    This page provides functions for management of
    SIP account settings on a remote NGNPro server,

    The authentication is done using a TLS client 
    certificate

*/

require("/etc/cdrtool/global.inc");
require("/etc/cdrtool/ngnpro_engines.inc");
require('sip_settings.php');

if ($credentials=getSipAccountFromX509Certificate()) {
    $account	 = $credentials['account'];
    $sip_engine  = $credentials['engine'];
    
    $reseller  	 = $credentials['reseller'];
    $customer  	 = $credentials['customer'];
    $login_type  = "subscriber";
} else {
    die('X.509 Credentials error');
}

$_class='SIPSettings';

$_reseller_class=$_class.$reseller;

if (class_exists($_reseller_class)) {
	$SipSettings_class=$_reseller_class;
} else {
	$SipSettings_class=$_class;
}

$login_credentials=array(
                        'reseller'       => $reseller,
                        'customer'       => $customer,
                        'login_type'     => $login_type,
                        'sip_engine'     => $sip_engine,
                        'templates_path' => './resellers/template'

);

renderUI($SipSettings_class,$account,$login_credentials,$soapEngines);

?>
