<?
$title="Login";
include("header.phtml");
?>

<script language="javascript" src="md5.js"></script>
<script language="javascript">

  function doChallengeResponse() {
    str = document.login.username.value + ":" +
          MD5(document.login.password.value) + ":" +
          document.login.challenge.value;

    document.login.response.value = MD5(str);
    items = document.login.username.value.split("@");
    if (items.length == 2) {
       username = items[0];
       domain = items[1];
    } else {
       username = domain = "";
    }
    str = username + ":" + domain + ":" + document.login.password.value;
    document.login.response_ha1.value = MD5(str);
    document.login.password.value = "";
    document.login.submit();
  }

</script>
<?
print "<div class=row-fluid><div id=wrapper2><div class=\"page-header\"><h2>";
print _("Login");
print "</h2></div>";
?>

<!-- failed login code -->
<?  
if ($username) {
    print "<div class='alert alert-error'>";
    print _("Either your SIP account or password are invalid");

    print "
    </div>
    <p>$login_msg</p>";

}
?>

    <form class='form-horizontal' action="<?php print $this->url() ?>" method=post name=login>

<?
print "<div class=control-group>
        <label class='control-label'>";
print _("SIP address");
print "</label>";
?>


        <div class=controls>
            <input type="text" name="username"
        value="
<?php
if (isset($this->auth["uname"])) {
    print $this->auth["uname"];
} else if (isset($_REQUEST['username'])) {
    print $_REQUEST['username'];
}
?>" placeholder="Example: 
<?php
if ($example_domain) {
    print "account@$example_domain";
} else {
    print "account@example.com";
}
?>" size=35 maxlength=50 class='span11'></div></div>

<?php
print "
                <div class=control-group>
                    <label class='control-label'>";
print _("Password");
print "
                    </label>
";
?>

                <div class='controls'>
                    <input type="password" name="password" size=35 maxlength=50 class='span11'></td>
                    <input type="hidden" name="step" value=<?php print $step?>>

<?php

$use_yubikey=0;
if (stream_resolve_include_path('Auth/Yubico.php')) {
    require_once 'Auth/Yubico.php';
    $use_yubikey=1;
}

if ($use_yubikey == 1 ) {
    print "</div></div>
    <div class=control-group>
    <label class=control-label>";
    print _("Yubikey");
    print "</label><div class=controls>";
    print '
        <input rel="popover" placeholder="This field is optional" data-trigger="hover" data-delay="1000" data-original-title="OTP hardware authentication" data-content="With this field you can login using a hardware OTP device called \'yubikey\'.<br/><br>
    		You can set your yubikey-id in the SIP settings page after you login with your SIP account and pasword.<br>
                <br/>
                For info and purchase of this key see <a href=\'http://www.yubico.com\' target=\'_blank\'>http://www.yubico.com</a>" type="text" name="yubikey" size="35">
        <p class="help-block"><a href=sip_login_reminder.phtml>';
        print _("SIP address or password forgotten?");
    print "
    </a></p>
    </div>
    </div>";
} else {
    print '<p class="help-block"><a href=sip_login_reminder.phtml>';
        print _("SIP address or password forgotten?");
    print "
    </a></p>
    </div>
    </div>";
}

$sess->hidden_session(); ?>
            <p class="help-block">
                <a href=sip_login_reminder.phtml>
                    SIP address or password forgotten?
                </a>
            </p>
            <div class='form-actions'>
                <input class='btn btn-primary' onClick="doChallengeResponse(); return false;" type="submit" name="submitbtn" value="Login now">
            </div>

<?
?>

<!-- Set up the form with the challenge value and an empty reply value -->
                <input type="hidden" name="challenge" value="<?php print $challenge ?>">
                <input type="hidden" name="response"  value="">
                <input type="hidden" name="response_ha1"  value="">
            </form>
        </div>
    </div>
</body>
<script language="JavaScript">
  // Activate the appropriate input form field.
  if (document.login.username.value == '') {
    document.login.username.focus();
  } else {
    document.login.password.focus();
  }

</script>

</html>
