<?
require("/etc/cdrtool/global.inc");
require("/etc/cdrtool/ngnpro_engines.inc");
require('sip_settings.php');

if ($credentials=getSipAccountFromHTTPDigest()) {
    $account	 = $credentials['account'];
    $sip_engine  = $credentials['engine'];
    
    $reseller  	 = $credentials['reseller'];
    $customer  	 = $credentials['customer'];
    $login_type  = "subscriber";
} else {
    die('HTP digest Credentials error');
}

$_class='SipSettings';
$_reseller_class=$_class.$reseller;

if (class_exists($_reseller_class)) {
	$SipSettings_class=$_reseller_class;
} else {
	$SipSettings_class=$_class;
}

$login_credentials=array(
                        'reseller'       => $reseller,
                        'customer'       => $customer,
                        'login_type'     => $login_type,
                        'sip_engine'     => $sip_engine,
                        'templates_path' => './templates'

);

renderUI($SipSettings_class,$account,$login_credentials,$soapEngines);

?>
