<?
header("Cache-Control: no-cache, must-revalidate");  // HTTP/1.1
header("Pragma: no-cache");
include("./global.inc");
page_open(
            array("sess" => "CDRTool_Session",
                  "auth" => "CDRTool_Auth",
                  "perm" => "CDRTool_Perm"));

$title="SIP settings page";

//$verbose=1;

if (is_readable("local/header.phtml")) {
    include("local/header.phtml");
} else {
    include("header.phtml");
}

$perm->check("provisioning");

require_once('provisioning/sip_settings_lib.phtml');
require_once("provisioning/ngnpro_engines.inc");
include_once("local/provisioning.phtml");

$account = $_REQUEST['account'];
$action  = $_REQUEST['action'];
$export  = $_REQUEST['export'];

$_class='SipSettings';
$_reseller_class=$_class.$_REQUEST['reseller'];

if (class_exists($_reseller_class)) {
	$SipSettings_class=$_reseller_class;
} else {
	$SipSettings_class=$_class;
}

$login_credentials=array(
                        'login_type'  => 'admin',
                        'reseller'   => $_REQUEST['reseller']
                        );

if ($resellerFilters[$login_credentials['reseller']]) {
	$login_credentials['soap_engine']      = $resellerFilters[$login_credentials['reseller']]['soap_engine'];
} else if ($_REQUEST['soap_engine']) {
    $login_credentials['soap_engine']=$_REQUEST['soap_engine'];
} else if ($resellerFilters['default']) {
	$login_credentials['soap_engine']      = $resellerFilters['default']['soap_engine'];
}

$SipSettings = new $SipSettings_class($account,$login_credentials,$soapEngines);

if (!$export) {
    $title  = "SIP settings of $account";
    $header = $SipSettings->headerFile;
    $css    = $SipSettings->cssFile;
    include($header);
    include($css);
}

if ($action=="Save settings") {
    if ($SipSettings->checkSettings()) {
        $SipSettings->saveSettings();
        unset($SipSettings);
        if (in_array($domain,$freeDomains)) {
            $SipSettings = new $SipSettings_class($account,$login_credentials,$soapEngines);
        } else {
            $SipSettings = new $SipSettings_class($account,$login_credentials,$soapEngines);
        }
    } else {
        print "<font color=red>";
        printf (_("Error: %s"),$SipSettings->error);
        print "</font>";
    }
} else if ($action=="set barring prefixes") {
    $SipSettings->setBarringPrefixes();
} else if ($action=="set presence") {
    $SipSettings->setPresence();
} else if ($action=="set reject members") {
    $SipSettings->setRejectMembers();
} else if ($action=="set accept rules") {
    $SipSettings->setAcceptRules();
} else if ($action=="set aliases") {
    $SipSettings->setAliases();
} else if ($action=="Send settings") {
    $SipSettings->sendEmail();
} else if ($tab=="phonebook" && $export) {
    $SipSettings->exportPhonebook($userAgent);
}

if (!$export) {
	$SipSettings->showAccount();
    print "
    </body>
    </html>
    ";
}

page_close();
?>
