<?
include("./global.inc");
page_open(
            array("sess" => "CDRTool_Session",
                  "auth" => "CDRTool_Auth",
                  "perm" => "CDRTool_Perm"));

$title="SIP settings page";

if (is_readable("local/header.phtml")) {
    include("local/header.phtml");
} else {
    include("header.phtml");
}

//$verbose=1;
if ($verbose) {
for (reset   ($HTTP_POST_VARS); list ($k, $v) = each  ($HTTP_POST_VARS); )
    if ($v) {
        $vars=$vars." <b>".$k."</b>='".$v."', ";
    }
    for (reset   ($HTTP_GET_VARS); list ($k, $v) = each  ($HTTP_GET_VARS); )
    if ($v) {
        $vars=$vars." <b>".$k."</b>='".$v."', ";
    }
    print_r($vars);
}

$perm->check("provisioning");

require_once('provisioning/sip_settings_lib.phtml');
include_once("provisioning/ngnpro_engines.inc");

list($username,$domain)=explode("@",$account);

$_class='SIPSettings';
$_reseller_class=$_class.$_REQUEST['reseller'];

if (class_exists($_reseller_class)) {
	$SIPSettings_class=$_reseller_class;
} else {
	$SIPSettings_class=$_class;
}

$loginCredentials=array(
                        'loginType'           => 'admin',
                        'reseller'            => $_REQUEST['reseller'],
                        'soapEngineIdSipPort' => $_REQUEST['soapEngineIdSipPort']
                        );

$SIPSettings = new $SIPSettings_class($account,$loginCredentials,$soapEngines);

if (!$export) {
    $title  = "SIP settings of $account";
    $header = $SIPSettings->headerFile;
    $css    = $SIPSettings->cssFile;
    include($header);
    include($css);
}

if ($action=="Save settings") {
    if ($SIPSettings->checkSettings()) {
        $SIPSettings->saveSettings();
        unset($SIPSettings);
        if (in_array($domain,$freeDomains)) {
            $SIPSettings = new $SIPSettings_class($account,$loginCredentials,$soapEngines);
        } else {
            $SIPSettings = new $SIPSettings_class($account,$loginCredentials,$soapEngines);
        }
    } else {
        print "<font color=red>";
        printf (_("Error: %s"),$SIPSettings->error);
        print "</font>";
    }
} else if ($action=="set barring prefixes") {
    $SIPSettings->setBarringPrefixes();
} else if ($action=="set presence") {
    $SIPSettings->setPresence();
} else if ($action=="set reject members") {
    $SIPSettings->setRejectMembers();
} else if ($action=="set accept rules") {
    $SIPSettings->setAcceptRules();
} else if ($action=="set aliases") {
    $SIPSettings->setAliases();
} else if ($action=="Send settings") {
    $SIPSettings->sendEmail();
} else if ($tab=="phonebook" && $export) {
    $SIPSettings->exportPhonebook($userAgent);
}

if (!$export) {
	$SIPSettings->showAccount();
    print "
    </body>
    </html>
    ";
}

page_close();
?>
