<?php
print "<!DOCTYPE html>\n";
print "<html lang='en'>\n";
print "<head>\n";
print "<title>$title</title>\n";
print "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
print "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=Windows-1250\">";
if ($autoRefeshTab) {
	print "<meta http-equiv=refresh content=$autoRefeshTab>";
}
print "<link href=\"bootstrap/css/bootstrap.css\" rel=\"stylesheet\">\n";
print "<link href=\"bootstrap/css/bootstrap-responsive.css\" rel=\"stylesheet\">\n";
print "</head>\n";
print "<body link=#000066>
";

?>

    <script src="bootstrap/js-used/jquery.js"></script>
    <script src="bootstrap/js-used/bootstrap-transition.js"></script>
    <script src="bootstrap/js-used/bootstrap-scrollspy.js"></script>
    <script src="bootstrap/js-used/bootstrap-tooltip.js"></script>
    <script src="bootstrap/js-used/bootstrap-popover.js"></script>
    <script src="bootstrap/js-used/application.js"></script>
