<?
include("../global.inc");
page_open(
    array("sess" => "CDRTool_Session",
          "auth" => "CDRTool_Auth",
          "perm" => "CDRTool_Perm"
          ));

$perm->check("statistics");

include("../cdrlib.phtml");

$title=$CDRTool['provider']['name']. " - SER Online users";
include("../header.phtml");
print "<h2>$title</h2>";
print "<p>";

if ($_REQUEST['datasource']) {
	$datasource=$_REQUEST['datasource'];
} else {
	$datasource='ser_radius';
}

$expandAll=$_REQUEST['expandAll'];

$online= new SIPonline($datasource);
$online->showAll($_REQUEST['domain']);

$REMOTE_ADDR        = $_SERVER['REMOTE_ADDR'];
$db =new DB_CDRTool;
$loginname=$auth->auth["uname"];

$log_query=sprintf("insert into log
(date,login,ip,datasource,description)
values (NOW(),'%s','%s','Registrar','View online users')",
addslashes($loginname),
addslashes($REMOTE_ADDR)
);
dprint($log_query);
$db->query($log_query);

page_close();

?>
