#! /bin/sh
#
### BEGIN INIT INFO
# Provides:          cdrtool
# Required-Start:    $syslog $network $local_fs $time
# Required-Stop:     $syslog $network $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the CDRTool rating engine
# Description:       Start the CDRTool rating engine
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
CDRTOOL_PATH=/var/www/CDRTool
DAEMON=$CDRTOOL_PATH/scripts/ratingEngine.php
NAME=cdrtool
DESC=cdrtool
RUN_ratingEngine=no

. /lib/lsb/init-functions

test -x $DAEMON || exit 0

# Include cdrtool defaults if available
if [ -f /etc/default/cdrtool ] ; then
    . /etc/default/cdrtool
fi

if [ "$RUN_ratingEngine" != "yes" ]; then
    echo "CDRTool is not yet configured. Edit /etc/default/cdrtool first."
    exit 0
fi

set -e

start() {
    echo -n "Starting CDRTool $DESC"
    start-stop-daemon --start --background --quiet --pidfile /var/run/ratingEngine.pid \
		--exec $DAEMON -- $DAEMON_OPTS
    echo "."
}

stop () {
    echo -n "Stopping CDRTool $DESC"
    start-stop-daemon --stop --quiet --oknodo --signal 15 --pidfile /var/run/ratingEngine.pid
    echo "."
}

reload () {
    echo -n "Reloading CDRTool rating tables:"
    echo
    $CDRTOOL_PATH/scripts/reloadRatingTables.php && true
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    reload|force-reload)
        reload
        ;;
    restart)
        stop
        #sleep 1
        start
        ;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
	exit 1
	;;
esac

exit 0
