<?
include("../../global.inc");
if ($SOAPServer['location']) {
    Header("Content-type: text/xml");
    Header("Content-Disposition: inline; filename=CDRTool.wsdl");
    header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
    header("Cache-Control: no-cache, must-revalidate");  // HTTP/1.1
    header("Pragma: no-cache");
    $wsdl=file_get_contents("CDRTool.wsdl");
    $wsdl=preg_replace("/SOAPLOCATION/",$SOAPServer['location'],$wsdl);
    print $wsdl;
} else {
    print "Please define \$SOAPServer['location'] in global.inc\n";
}
?>
